### ISSUE TITLE
send json string to countly

### ISSUE THREAD

**Issue by SilentFlute** [Countly/countly-sdk-web#76]
Hi Guys,
I use `countly-sdk-web` in my `nextjs react` project, and cause `ssr` mode i think, when i use `yarn add countly-sdk-web` and `import Countly from 'countly-sdk-web'` it throw a error, so i find the `countly.min.js` out and add it to the `script` append to `dom`, then i init it:
```
Countly.q = [];
Countly.app_key = 'my app key';
Countly.url = 'my api url';
Countly.init();
```
there is a new case: i need detect how long a user views a list item, in that case, i need commit the list item info to `countly`, the valid items of course, that means in `custom event`, the `segmentation` may like this, and include user's info as well:
```
<div
  onClick={
    () => {
      const { Countly } = window;

      const obj = {
        user: {
          id: 1,
          createTime: 2,
          mobile: 3
        },
        listItem: [
          {
            a: 1,
            b: 2
          },
          {
            c: 3,
            d: 4
          }
        ],
        other1: 'other1',
        other2: 'other2'
      };

      for (const k in obj) {
        const ele = obj[k];
        obj[k] = JSON.stringify(ele);
      }

      Countly.q.push(['add_event', {
        'key': 'next-project-list-item-observe',
        'segmentation': obj
      }]);

      console.log(obj);
    }
  }
>press me</div>
```
`console.log` statement output is expected:
```
{
  listItem: '[{"a":1,"b":2},{"c":3,"d":4}]',
  other1: '"other1"',
  other2: '"other2"',
  user: '{"id":1,"createTime":2,"mobile":3}'
}
```
the api interface returns success as well, but in the management platform, the `listItem` and `user` segmentation is `No data`:
![image](https://user-images.githubusercontent.com/28900312/94387323-69f26d80-017c-11eb-9850-2521de152dd3.png)
`other1` and `other2` are go well of course, i check the `network` find the result returns well:
![image](https://user-images.githubusercontent.com/28900312/94387591-2fd59b80-017d-11eb-8c0a-cc03b42adbdc.png)
in the earlier time, a tried sth like this:
```
'segmentation': {
  'a': '{a: 1, b: 2}'
}
```
```
'segmentation': {
  'b': '"{a: 1, b: 2}"'
}
```
```
'segmentation': {
  'c': JSON.stringify({a:1, b:2})
}
```
and
```
'segmentation': {
  'd': {a:1, b:2}
}
```
and check these in the management platform, it confused a lot:
![image](https://user-images.githubusercontent.com/28900312/94388576-0b2ef300-0180-11eb-94a5-29eaf1841799.png)
`{a. 1, b. 2}` `"{a. 1, b. 2}"`, seriously??How could be `a dot 1`?The api results are returned as expected i can see in the above, but how??And as u can see, in segmentation `c`, i used `JSON.stringify`, but the result shown in the management is `No data`...
So is there a way to send a json string to the `countly` use `segmentation`?Or another way can do it?
thanks

**Comment by ar2rsawseen** [comment]
Hello
no, unfortunately, we don't support nested objects or JSON like objects or JSON like strings on the server for event segmentation.
The results you experience are because of security concerns and escaping those values so they would not work as JSON anymore. And unfortunately, currently, we don't have plans to support those too, due to the underlying data structure (which is also JSON data in the database, so we make sure they won't collide or break the existing scheme).

If you need the list to be as a single value, I would suggest concatenating the list values with some string, like underscore (and order them if you need the list of the same items in different order to produce the same segment value)
If you need to be able to check/break down data by specific list item values, then you can either prefix list as keys and use them as segment keys or dispatch separate events for each value in the list.

**Comment by SilentFlute** [comment]
@ar2rsawseen what a brilliant idea, got it, and i really appreciate, thanks again
